config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
resources :flats
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])

    if @flat.update(flat_params)
      redirect_to @flat
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy

    redirect_to flats_path, status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit([:name,
      :address, :description, :price_per_night, :number_of_guests])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Submit", class:"btn btn-primary" %>
<% end %>

app/views/flats/edit.html.erb
<h1><%= "Editting #{@flat.name} flat" %></h1>

<%= render "form", flat: @flat %>

<br>

app/views/flats/index.html.erb
<h1>All our Flats</h1>
<%= link_to "Add flat", new_flat_path %>
<% @flats.each do |flat| %>
  <ol>
    <li>
      <h3><%= link_to flat.name,  flat_path(flat.id)%></h3>
      <ul>
        <li><p>Address: <%= flat.address %></p></li<>
        <li><p>Description: <%= flat.description%></p></li<>
        <li><p>Price per night: <%= flat.price_per_night%>$</p></li<>
        <li><p>Capacity: <%= flat.number_of_guests%></p></li<>
      </ul>
    </li>
  </ol>
  <% end %>

app/views/flats/new.html.erb
<div class="container">
  <h1>New Flat</h1>
  <%= render "form", flat: @flat %>
  <br>
  <%= link_to "Back to flats", flats_path%>
</div>

app/views/flats/show.html.erb
<ul>
  <li><p>Name:  <%= @flat.name %></p></li<>
  <li><p>Address: <%= @flat.address %></p></li<>
  <li><p>Description: <%= @flat.description%></p></li<>
  <li><p>Price per night: <%= @flat.price_per_night%>$</p></li<>
  <li><p>Capacity: <%= @flat.number_of_guests%></p></li<>
</ul>

<%= link_to 'Back to flats', flats_path %>
<%= link_to 'Edit this flat', edit_flat_path(@flat) %>
<%= link_to "Delete this flat",
    flat_path(@flat),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>